services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: hyperroute-db
    environment:
      POSTGRES_DB: hyperroute
      POSTGRES_USER: hyperuser
      POSTGRES_PASSWORD: hyperpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
